---

# Stateless app server configuration, designed to be used with external mysql,
# mongo, rabbitmq, and elasticsearch services.

- name: Configure instance(s)
  hosts: stateless
  sudo: True
  gather_facts: True

  vars:
    migrate_db: 'yes'
    openid_workaround: True
    EDXAPP_LMS_NGINX_PORT: '80'
    ENABLE_ECOMMERCE: False  # Disable ecommerce by default
    EDXAPP_MONGO_HOSTS: "{{ groups['datastores'] }}"
    EDXAPP_MYSQL_HOST: "13.126.6.71"
    EDXAPP_MYSQL_CSMH_HOST: "13.126.6.71"
    EDXAPP_ELASTIC_SEARCH_CONFIG:
      - host: "{{ groups['datastores'][0] }}"
        port: 9200
    EDXAPP_MEMCACHE: ["{{ groups['datastores'][0] }}:11211"]
    EDXAPP_RABBIT_HOSTNAME: "{{ groups['datastores'][0] }}"
    FORUM_MONGO_HOSTS: "{{ groups['datastores'] }}"
    FORUM_ELASTICSEARCH_HOST: "{{ groups['datastores'][0] }}"
    XQUEUE_RABBITMQ_HOSTNAME: "{{ groups['datastores'][0] }}"
    XQUEUE_MYSQL_HOST: "{{ groups['datastores'][0] }}"
  roles:
    - role: ecommerce
    - role: ecomworker
