WHITELABEL_THEME_DIR: "edx-themes"

WHITELABEL_COURSE_TITLE: "test_course"
WHITELABEL_COURSE_RUN: "2017"
WHITELABEL_MODULE_STORE: "split"

WHITELABEL_MYSQL_COMMANDS:
  - "CREATE SCHEMA {{ DISCOVERY_DEFAULT_DB_NAME }};"
  - "CREATE USER '{{ DISCOVERY_MYSQL_USER }}'@'{{ DISCOVERY_MYSQL }}' IDENTIFIED BY '{{ DISCOVERY_MYSQL_PASSWORD }}';"
  - "GRANT CREATE, DROP, DELETE, INSERT, SELECT, UPDATE, ALTER, INDEX ON {{ DISCOVERY_DEFAULT_DB_NAME }}.* TO '{{ DISCOVERY_MYSQL_USER }}'@'{{ DISCOVERY_MYSQL }}';"
